---
apiVersion: v1
kind: Service
metadata:
  name: dev-service
  labels:
    app: dev
    app.kubernetes.io/instance: argocd-app
spec:
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
  selector:
    app: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-deploy
  labels:
    app: dev
spec:
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: nginx
        image: wil42/playground:v2
        ports:
        - containerPort: 8888

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-ingress
  labels:
    app: dev
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-service
            port:
              number: 8888
